version: '3'

services:
  payments-db:
    container_name: payments_database
    image: 'mongo:7.0'
    restart: always
    volumes:
      - ./mongo:/data/db
    ports:
      - ${MONGO_DB_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
